{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressclass }}
    nginx.ingress.kubernetes.io/enable-cors: {{ .Values.ingress.enablecors }}
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.ingress.corsalloworigin }}
    nginx.ingress.kubernetes.io/cors-allow-headers: {{ .Values.ingress.corsallowheaders }}
    nginx.ingress.kubernetes.io/cors-expose-headers: {{ .Values.ingress.corsexposeheaders }}
    nginx.ingress.kubernetes.io/cors-allow-methods: {{ .Values.ingress.corsallowmethod }}
    nginx.ingress.kubernetes.io/cors-allow-credentials: {{ .Values.ingress.corsallowcredentials }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxybodysize }}
spec:
  ingressClassName: {{ .Values.ingress.ingressclass }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.serviceName }}
                port:
                  number: {{ .Values.ingress.portNumber }}
{{- end }}