apiVersion: v1
kind: Service
metadata:
  name: denizbank-brm-rest-api
  labels:
    app: denizbank-brm-rest-api
spec:
  selector:
    app: denizbank-brm-rest-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: LoadBalancer
