replicaCount: 1

image:
  self: linktera/brm:denizbank-ui-v1.0.30
  policy: IfNotPresent
  env:
    api: ltbrmapp.apps.uat.deniz.denizbank.com

service:
  type: LoadBalancer
  port: 3000
  name: https

ingress:
  enabled: true
  name: brm-ui-denizbank
  namespace: brm
  ingressclass: nginx
  host: ltbrm.apps.uat.deniz.denizbank.com
  path: /
  serviceName: denizbank-ui
  portNumber: 80
  enablecors: "true"
  corsalloworigin: "*"
  corsallowheaders: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-ms-useragent,ocp-apim-subscription-key"
  corsexposeheaders:  "*"
  corsallowmethod: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
  corsallowcredentials: "false"
  proxybodysize: "500m"
