apiVersion: v1
kind: Service
metadata:
  name: denizbank-ui
  labels:
    app: denizbank-ui
spec:
  selector:
    app: denizbank-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer
